apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: openshift-gitops
  source:
    repoURL: https://github.com/diesello/argo_demo
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true  
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: route.openshift.io
      kind: Route
      jsonPointers:
        - /spec/host
        - /status
        - /metadata/annotations/openshift.io~1host.generated