apiVersion: batch/v1
kind: Job
metadata:
  generateName: nginx-presync-fail-
  namespace: nginx
  annotations:
    argocd.argoproj.io/hook: PreSync
    #argocd.argoproj.io/hook-delete-policy: HookFailed
    argocd.argoproj.io/sync-wave: "-1"
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: fail
          image: registry.access.redhat.com/ubi9/ubi-minimal:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Intentional PreSync failure for ArgoCDSyncAlert testing"
              exit 1
