apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx-route
  namespace: nginx
  labels:
    app: nginx
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: nginx-lab
    weight: 100
  wildcardPolicy: None